<?php

namespace JobPortl\JPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
	public function findAdminByName($name)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT a.adminId FROM JobPortlJPBundle:Admin a where a.user_name=' . $name
			)
			->getResult();
	}
}
