<?php

namespace JobPortl\JPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostingRepository extends EntityRepository
{

}
